vqvae_name: PMPNN_OTVQ_CPD_LM
lm_path: /Mounts/rbg-storage1/users/johnyang/s2sDM/pkl_jar/ckpt/FT_PMPNN_OTVQ_hp_search_2/epoch=57-step=9570.ckpt
codebook_size: 10
hparams_file: /Mounts/rbg-storage1/users/johnyang/s2sDM/multirun/2023-01-04/12-00-52/2/.hydra/cfg_for_latent_diff.yaml