vqvae_name: PMPNN_OTVQ_MESMCPD_LM
lm_path: '/Mounts/rbg-storage1/users/johnyang/s2sDM/notebooks/artifacts/model-3v53d52m:v102/model.ckpt'
codebook_size: 80
hparams_file: /Mounts/rbg-storage1/users/johnyang/s2sDM/outputs/2023-01-29/03-10-26/.hydra/config.yaml