defaults:
  - OTVQ_MESMCPD_exp

experiment:
  name: OTVQ_MESMCPD_pred_exp
  mode: predict
  ckpt_path: /Mounts/rbg-storage1/users/johnyang/s2sDM/notebooks/artifacts/model-3v53d52m:v102/model.ckpt
  

lm:
  save_name: ${experiment.name}
  pred_cfg:
    save_name: ${experiment.name}
    save_dir: ${lm.pred_cfg.data_dir}/${lm.pred_cfg.save_name}/