defaults:
 - PMPNN_Abs_exp
 - lm/latent_model: OT_10
 - override lm/token: VQ_Latent

experiment:
  name: PMPNN_Abs_Trmr_Latent_OT_10

lm:
  save_name: ${experiment.name}
  num_classes: 11
  lm_name: Latent_Absorbing_Diff_LM
  model:
    name: PMPNN_Trmr_Latent_Diff
    nheads: 4
    num_layers: 3
    dropout: 0.1
    absorbing: True
    num_classes: ${lm.num_classes}
    embedding_cfg:
      max_len: ${dm.max_protein_length}
      T: ${lm.num_timesteps}
      input_size: ${lm.num_classes} # relevant for codebook size.
      pos_embed_size: 64
      output_embed_size: ${lm.model.hidden_dim}

dm:
  alphabet: ACDEFGHIKLMNPQRSTVWY