defaults:
 - PMPNN_Uniform_S_Latent_FT_exp

experiment:
  name: PMPNN_Uniform_S_Latent_FT_pred
  mode: predict
  ckpt_path: /Mounts/rbg-storage1/users/johnyang/s2sDM/pkl_jar/ckpt/PMPNN_Uniform_Latent_OT_10_FT/epoch=314-step=29295.ckpt

lm:
  save_name: ${experiment.name}